### ISSUE TITLE
Ezra Bridger bug

### ISSUE THREAD

**Issue by adbronico** [SWU-Karabast/SWUOnline#32]
Ezra's ability should only trigger if he attacks and survives. Currently, this triggers on every attack.

**Comment by adbronico** [comment]
Also, not a bug but I've checked out the codebase locally to try to help out - I will try to fix this one.

I have a question about how the GeneratedCardDictionaries file is created. For referencing cards like Ezra, I see in CombatChain this:
case "9560139036"://Ezra Bridger
which makes me wonder how individual cards are being stored? It seems like it could be improved, but I was looking for more context before attempting it myself.

**Comment by OotTheMonk** [comment]
GeneratedCardDictionaries is created by zzCardCodeGenerator. It pulls a
json of all the card data from the FFG api and uses it to generate that
code dictionary. This is because with php optimization, it allows for
extremely fast in-memory lookup for all the card data. One notable
improvement would be to have it generate a keyed array dictionary instead
of the trie switch statements. Someone performance tested that and found it
to be about 10-30% faster I believe.

**Comment by OotTheMonk** [comment]
This is fixed!
